devel/py-generate: Fix MASTER_SITES, Remove BROKEN [1]
While I'm here, address other ports bugs/issues [2]:

  - gmake is not required (build uses distutils/setuptools:Extension)
  - patch setup.py:version (was 2.2) to match PORTVERSION (2.8)
  - Remove unecessary DISTNAME override
  - Strip installed extension/library
  - Correctly declare USES=python:<version-spec>, limited to 2.7. Fails to
    import on Python 3:

      ImportError: ... /site-packages/generate.so: Undefined symbol "PyString_FromString

PR:		241966
Submitted by:	D'Arcy J.M. Cain <darcy druid net> [1]
Approved by:	portmgr (blanket(s): ports compliance, dependencies) [2]
MFH:		2020Q1 (blanket(s): build (fetch) fix, ports compliance) [1][2]